# Generated by Django 4.2.16 on 2024-11-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crewID', models.IntegerField()),
                ('courseName', models.CharField(max_length=256)),
                ('courseTimeSlot', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Crews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crewName', models.CharField(max_length=256)),
                ('crewCaptain', models.IntegerField()),
                ('email', models.CharField(max_length=256)),
                ('mobile', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Crews',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrewID', models.IntegerField()),
                ('FirstName', models.CharField(max_length=256)),
                ('LastName', models.CharField(max_length=256)),
                ('Email', models.CharField(max_length=256)),
                ('Mobile', models.CharField(max_length=256)),
                ('SplitPartner', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Players',
            },
        ),
        migrations.CreateModel(
            name='TeeTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrewID', models.IntegerField()),
                ('gDate', models.DateField()),
                ('CourseID', models.IntegerField()),
                ('P1ID', models.IntegerField()),
                ('P2ID', models.IntegerField()),
                ('P3ID', models.IntegerField()),
                ('P4ID', models.IntegerField()),
            ],
            options={
                'db_table': 'TeeTimes',
            },
        ),
        migrations.CreateModel(
            name='TeeTimesInd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrewID', models.IntegerField()),
                ('gDate', models.DateField()),
                ('CourseID', models.IntegerField()),
                ('PID', models.IntegerField()),
            ],
            options={
                'db_table': 'TeeTimesInd',
            },
        ),
    ]
