# Generated by Django 4.2.16 on 2024-11-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teetimesind',
            name='CourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.courses'),
        ),
        migrations.AlterField(
            model_name='teetimesind',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.players'),
        ),
    ]
