# Generated by Django 4.2.16 on 2024-12-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0003_log_subswap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subswap',
            name='SwapID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
