# Generated by Django 4.2.16 on 2024-12-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0004_alter_subswap_swapid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='OfferID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='ReceiveID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='RefID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='RequestDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='Status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
