# Generated by Django 4.2.16 on 2024-12-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0005_alter_log_offerid_alter_log_receiveid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subswap',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.players'),
        ),
        migrations.AlterField(
            model_name='subswap',
            name='TeeTimeIndID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.teetimesind'),
        ),
    ]
