# Generated by Django 4.2.16 on 2025-01-06 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GRPR', '0006_alter_subswap_pid_alter_subswap_teetimeindid'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='User',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='players',
            name='FirstName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='players',
            name='LastName',
            field=models.CharField(max_length=30),
        ),
    ]
