# Generated by Django 4.2.16 on 2025-01-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0007_players_user_alter_players_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='players',
            old_name='User',
            new_name='user',
        ),
    ]
