# Generated by Django 4.2.16 on 2025-01-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0009_loginactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeeTimes',
        ),
    ]
