# Generated by Django 4.2.16 on 2025-01-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0010_delete_teetimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrewID', models.IntegerField()),
                ('xDate', models.DateField()),
                ('rDate', models.DateField()),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.players')),
            ],
            options={
                'db_table': 'Xdates',
            },
        ),
    ]
