# Generated by Django 4.2.16 on 2025-02-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0011_xdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='subswap',
            name='SubStatus',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='subswap',
            name='SubType',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='subswap',
            name='nStatus',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='subswap',
            name='nType',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
