# Generated by Django 4.2.16 on 2025-02-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0012_subswap_substatus_subswap_subtype_subswap_nstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subswap',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='subswap',
            name='Type',
        ),
    ]
