# Generated by Django 4.2.16 on 2025-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0013_remove_subswap_status_remove_subswap_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=15)),
                ('message_body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SMSResponse',
            },
        ),
        migrations.AlterField(
            model_name='subswap',
            name='nStatus',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='subswap',
            name='nType',
            field=models.CharField(max_length=32),
        ),
    ]
