# Generated by Django 4.2.16 on 2025-03-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0014_smsresponse_alter_subswap_nstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='Member',
            field=models.IntegerField(null=True),
        ),
    ]
