# Generated by Django 4.2.16 on 2025-03-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0016_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrewID', models.IntegerField()),
                ('rDate', models.DateField()),
            ],
            options={
                'db_table': 'Mdates',
            },
        ),
    ]
