# Generated by Django 4.2.16 on 2025-03-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0017_mdates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mdates',
        ),
    ]
