# Generated by Django 4.2.16 on 2025-03-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0018_delete_mdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CrewID', models.IntegerField()),
                ('CreateDate', models.DateField()),
                ('PlayDate', models.DateField()),
                ('Status', models.IntegerField(blank=True, null=True)),
                ('CreateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.players')),
            ],
            options={
                'db_table': 'Games',
            },
        ),
        migrations.CreateModel(
            name='ScorecardMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateField()),
                ('CreateID', models.IntegerField()),
                ('PlayDate', models.DateField()),
                ('CourseID', models.IntegerField()),
                ('TeeID', models.IntegerField(blank=True, null=True)),
                ('GroupID', models.IntegerField()),
                ('CrewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.crews')),
                ('GameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.games')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.players')),
            ],
            options={
                'db_table': 'ScorecardMeta',
            },
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateField()),
                ('AlterDate', models.DateField()),
                ('Hole', models.IntegerField()),
                ('RawScore', models.IntegerField()),
                ('NetScore', models.IntegerField()),
                ('AlterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.players')),
                ('smID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.scorecardmeta')),
            ],
            options={
                'db_table': 'Scorecard',
            },
        ),
        migrations.CreateModel(
            name='GameInvites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlterDate', models.DateField()),
                ('Status', models.IntegerField(blank=True, null=True)),
                ('GameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.games')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.players')),
            ],
            options={
                'db_table': 'GameInvites',
            },
        ),
    ]
