# Generated by Django 4.2.16 on 2025-03-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0019_games_scorecardmeta_scorecard_gameinvites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinvites',
            name='Status',
            field=models.CharField(default='Pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='games',
            name='Status',
            field=models.CharField(default='Pending', max_length=32),
        ),
    ]
