# Generated by Django 4.2.16 on 2025-03-25 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0020_alter_gameinvites_status_alter_games_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvites',
            name='TTID',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='GRPR.teetimesind'),
            preserve_default=False,
        ),
    ]
