# Generated by Django 4.2.16 on 2025-03-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0021_gameinvites_ttid'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='GHIN',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='players',
            name='Index',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
