# Generated by Django 4.2.16 on 2025-03-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0022_players_ghin_players_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=128)),
                ('TeeID', models.IntegerField()),
                ('TeeName', models.CharField(max_length=128)),
                ('CourseRating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('SlopeRating', models.IntegerField()),
                ('Par', models.IntegerField()),
                ('Yards', models.IntegerField()),
            ],
            options={
                'db_table': 'CourseTees',
            },
        ),
    ]
