# Generated by Django 4.2.16 on 2025-03-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0023_coursetees'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='CourseTeesID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GRPR.coursetees'),
        ),
    ]
