# Generated by Django 4.2.16 on 2025-03-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0024_games_courseteesid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetees',
            name='CourseID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
