# Generated by Django 4.2.16 on 2025-03-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0025_coursetees_courseid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardmeta',
            name='Index',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='scorecardmeta',
            name='NetHDCP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scorecardmeta',
            name='RawHDCP',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
