# Generated by Django 4.2.16 on 2025-03-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0026_scorecardmeta_index_scorecardmeta_nethdcp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecardmeta',
            name='GroupID',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
