# Generated by Django 4.2.16 on 2025-04-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0027_alter_scorecardmeta_groupid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecardmeta',
            name='TeeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GRPR.coursetees'),
        ),
    ]
