# Generated by Django 4.2.16 on 2025-04-02 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0028_alter_scorecardmeta_teeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoleNumber', models.IntegerField()),
                ('Par', models.IntegerField()),
                ('Yardage', models.IntegerField()),
                ('Handicap', models.IntegerField()),
                ('CourseTeesID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GRPR.coursetees')),
            ],
            options={
                'db_table': 'CourseHoles',
            },
        ),
    ]
