# Generated by Django 4.2.16 on 2025-04-03 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0029_courseholes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='Hole',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='GameID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GRPR.games'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='HoleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GRPR.courseholes'),
        ),
    ]
