# Generated by Django 4.2.16 on 2025-04-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0030_remove_scorecard_hole_scorecard_gameid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='Putts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
