# Generated by Django 4.2.16 on 2025-04-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0031_scorecard_putts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='AlterDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='CreateDate',
            field=models.DateTimeField(),
        ),
    ]
