# Generated by Django 4.2.16 on 2025-04-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0032_alter_scorecard_alterdate_alter_scorecard_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardmeta',
            name='NetIN',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='scorecardmeta',
            name='NetOUT',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='scorecardmeta',
            name='NetTotal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='scorecardmeta',
            name='Putts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='scorecardmeta',
            name='RawIN',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='scorecardmeta',
            name='RawOUT',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='scorecardmeta',
            name='RawTotal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
