# Generated by Django 4.2.16 on 2025-04-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0033_scorecardmeta_netin_scorecardmeta_netout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecardmeta',
            name='Skins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
