# Generated by Django 4.2.16 on 2025-04-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0034_scorecardmeta_skins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoleNumber', models.IntegerField()),
                ('SkinDate', models.DateField(auto_now_add=True)),
                ('GameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.games')),
                ('PlayerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.players')),
            ],
            options={
                'db_table': 'Skins',
                'unique_together': {('GameID', 'PlayerID', 'HoleNumber')},
            },
        ),
    ]
