# Generated by Django 4.2.16 on 2025-04-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0035_skins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skins',
            name='HoleNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.courseholes'),
        ),
    ]
