# Generated by Django 4.2.16 on 2025-04-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0036_alter_skins_holenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('CreatePerson', models.CharField(max_length=64)),
                ('AlterDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('AlterPerson', models.CharField(blank=True, max_length=64, null=True)),
                ('SentDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('SentPerson', models.CharField(blank=True, max_length=64, null=True)),
                ('SentVia', models.CharField(blank=True, max_length=64, null=True)),
                ('Msg', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'AutomatedMessages',
            },
        ),
    ]
