# Generated by Django 4.2.16 on 2025-04-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0037_automatedmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedmessages',
            name='AlterDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automatedmessages',
            name='SentDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
