# Generated by Django 4.2.16 on 2025-05-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0038_alter_automatedmessages_alterdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skins',
            name='Payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
