# Generated by Django 4.2.16 on 2025-05-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0039_skins_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Type',
            field=models.CharField(default='Skins', max_length=32),
            preserve_default=False,
        ),
    ]
