# Generated by Django 4.2.16 on 2025-05-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0040_games_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='Format',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='Min1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='Min18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='NumScores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
