# Generated by Django 4.2.16 on 2025-05-28 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0042_games_assocgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreateDate', models.DateField(auto_now_add=True)),
                ('AlterDate', models.DateField(auto_now_add=True)),
                ('CrewID', models.IntegerField()),
                ('GroupID', models.CharField(blank=True, max_length=16, null=True)),
                ('RawScore', models.IntegerField()),
                ('NetScore', models.IntegerField()),
                ('AlterID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altered_records', to='GRPR.players')),
                ('CreateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_records', to='GRPR.players')),
                ('GameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.games')),
                ('HoleNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.courseholes')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scoring', to='GRPR.players')),
            ],
            options={
                'db_table': 'Forty',
            },
        ),
    ]
