# Generated by Django 4.2.16 on 2025-05-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0043_forty'),
    ]

    operations = [
        migrations.AddField(
            model_name='forty',
            name='Par',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
