# Generated by Django 4.2.16 on 2025-05-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0044_forty_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forty',
            name='AlterDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forty',
            name='CreateDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
