# Generated by Django 4.2.16 on 2025-06-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0045_alter_forty_alterdate_alter_forty_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='IsLocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='games',
            name='LockedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
