# Generated by Django 4.2.16 on 2025-07-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0046_games_islocked_games_lockedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasCupPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(choices=[('PGA', 'PGA'), ('LIV', 'LIV')], max_length=3)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.games')),
                ('PID1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gascup_partner1', to='GRPR.players')),
                ('PID2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gascup_partner2', to='GRPR.players')),
            ],
            options={
                'db_table': 'GasCupPair',
            },
        ),
        migrations.CreateModel(
            name='GasCupScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NetScore', models.PositiveSmallIntegerField()),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.games')),
                ('Hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.courseholes')),
                ('Pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.gascuppair')),
            ],
            options={
                'db_table': 'GasCupScore',
                'unique_together': {('Pair', 'Hole')},
            },
        ),
        migrations.AddConstraint(
            model_name='gascuppair',
            constraint=models.UniqueConstraint(models.F('Game'), models.F('PID1'), name='gascuppair_unique_pid1'),
        ),
        migrations.AddConstraint(
            model_name='gascuppair',
            constraint=models.UniqueConstraint(models.F('Game'), models.F('PID2'), name='gascuppair_unique_pid2'),
        ),
        migrations.AddConstraint(
            model_name='gascuppair',
            constraint=models.UniqueConstraint(models.F('Game'), models.F('PID1'), models.F('PID2'), condition=models.Q(('PID1__lt', models.F('PID2'))), name='gascuppair_unique_ordered'),
        ),
    ]
