# Generated by Django 4.2.16 on 2025-07-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0047_gas_cup_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gascuppair',
            name='gascuppair_unique_pid1',
        ),
        migrations.RemoveConstraint(
            model_name='gascuppair',
            name='gascuppair_unique_pid2',
        ),
        migrations.RemoveConstraint(
            model_name='gascuppair',
            name='gascuppair_unique_ordered',
        ),
        migrations.AlterField(
            model_name='gascuppair',
            name='PID2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gascup_partner2', to='GRPR.players'),
        ),
    ]
