# Generated by Django 4.2.16 on 2025-07-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0048_remove_gascuppair_gascuppair_unique_pid1_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gascuppair',
            constraint=models.UniqueConstraint(fields=('Game', 'PID1'), name='gascuppair_unique_pid1'),
        ),
    ]
