# Generated by Django 4.2.16 on 2025-07-22 20:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0049_gascuppair_gascuppair_unique_pid1'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasCupOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slot', models.CharField(max_length=16)),
                ('PGA_pts', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3)),
                ('LIV_pts', models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3)),
                ('Front_txt', models.CharField(blank=True, max_length=32, null=True)),
                ('Back_txt', models.CharField(blank=True, max_length=32, null=True)),
                ('Overall_txt', models.CharField(blank=True, max_length=32, null=True)),
                ('Note', models.CharField(blank=True, max_length=128, null=True)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.games')),
            ],
            options={
                'db_table': 'GasCupOverride',
                'unique_together': {('Game', 'Slot')},
            },
        ),
    ]
