# Generated by Django 4.2.16 on 2025-07-30 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0050_gascupoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameToggles',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('gascup_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
