# Generated by Django 4.2.16 on 2025-09-03 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GRPR', '0051_gametoggles'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetupDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crew_id', models.IntegerField(db_index=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('tee_choice', models.CharField(blank=True, max_length=64)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_setup_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['created_by', 'is_complete'], name='GRPR_gamese_created_034520_idx')],
            },
        ),
    ]
