# Generated by Django 4.2.16 on 2025-09-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0052_gamesetupdraft'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gamesetupdraft',
            new_name='GameSetupDr_created_2cf6f4_idx',
            old_name='GRPR_gamese_created_034520_idx',
        ),
        migrations.AlterModelTable(
            name='gamesetupdraft',
            table='GameSetupDraft',
        ),
        migrations.AlterModelTable(
            name='gametoggles',
            table='GameToggles',
        ),
    ]
