# Generated by Django 4.2.16 on 2025-09-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0053_rename_grpr_gamese_created_034520_idx_gamesetupdr_created_2cf6f4_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
