# Generated by Django 4.2.16 on 2025-09-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0054_alter_userprofile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametoggles',
            name='fallclassic_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
