# Generated by Django 4.2.16 on 2025-09-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0055_gametoggles_fallclassic_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gascuppair',
            name='Team',
            field=models.CharField(choices=[('PGA', 'PGA'), ('LIV', 'LIV')], max_length=12),
        ),
    ]
