# Generated by Django 4.2.16 on 2025-10-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0056_alter_gascuppair_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetupdraft',
            name='anchor_game_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
