# Generated by Django 4.2.16 on 2025-10-09 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0057_gamesetupdraft_anchor_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StblTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('TeamID', models.PositiveSmallIntegerField()),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.games')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.players')),
            ],
            options={
                'indexes': [models.Index(fields=['Game', 'TeamID'], name='GRPR_stblte_Game_id_6eaa33_idx')],
                'unique_together': {('Game', 'PID')},
            },
        ),
        migrations.CreateModel(
            name='StblScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlterDate', models.DateTimeField(auto_now=True)),
                ('RawScore', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('NetScore', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Points', models.SmallIntegerField(default=0)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.games')),
                ('Hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.courseholes')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.players')),
            ],
            options={
                'indexes': [models.Index(fields=['Game', 'PID'], name='GRPR_stblsc_Game_id_dc2f1e_idx'), models.Index(fields=['Game'], name='GRPR_stblsc_Game_id_0a8e1a_idx')],
                'unique_together': {('Game', 'PID', 'Hole')},
            },
        ),
    ]
