# Generated by Django 4.2.16 on 2025-10-09 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0058_stblteam_stblscore'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stblscore',
            new_name='StblScore_Game_id_6994ed_idx',
            old_name='GRPR_stblsc_Game_id_dc2f1e_idx',
        ),
        migrations.RenameIndex(
            model_name='stblscore',
            new_name='StblScore_Game_id_168ec6_idx',
            old_name='GRPR_stblsc_Game_id_0a8e1a_idx',
        ),
        migrations.RenameIndex(
            model_name='stblteam',
            new_name='StblTeam_Game_id_ef5bc7_idx',
            old_name='GRPR_stblte_Game_id_6eaa33_idx',
        ),
        migrations.AlterModelTable(
            name='stblscore',
            table='StblScore',
        ),
        migrations.AlterModelTable(
            name='stblteam',
            table='StblTeam',
        ),
    ]
