# Generated by Django 4.2.16 on 2025-10-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0059_rename_grpr_stblsc_game_id_dc2f1e_idx_stblscore_game_id_6994ed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stblteam',
            name='TeamName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
