# Generated by Django 4.2.16 on 2025-10-14 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0060_stblteam_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='GHIN',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'GHIN must be exactly 13 digits')]),
        ),
    ]
