# Generated by Django 4.2.16 on 2025-10-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0061_alter_players_ghin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='Email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='Mobile',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddConstraint(
            model_name='players',
            constraint=models.UniqueConstraint(fields=('CrewID', 'FirstName', 'LastName'), name='uniq_player_name_per_crew'),
        ),
        migrations.AddConstraint(
            model_name='players',
            constraint=models.UniqueConstraint(condition=models.Q(('Email__isnull', False), models.Q(('Email', ''), _negated=True)), fields=('CrewID', 'Email'), name='uniq_email_per_crew_when_present'),
        ),
        migrations.AddConstraint(
            model_name='players',
            constraint=models.UniqueConstraint(condition=models.Q(('Mobile__isnull', False), models.Q(('Mobile', ''), _negated=True)), fields=('CrewID', 'Mobile'), name='uniq_mobile_per_crew_when_present'),
        ),
        migrations.AddConstraint(
            model_name='players',
            constraint=models.UniqueConstraint(condition=models.Q(('GHIN__isnull', False), models.Q(('GHIN', ''), _negated=True)), fields=('CrewID', 'GHIN'), name='uniq_ghin_per_crew_when_present'),
        ),
    ]
