# Generated by Django 4.2.16 on 2025-10-14 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRPR', '0062_alter_players_email_alter_players_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortyGroupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupID', models.CharField(max_length=16)),
                ('NumScores', models.PositiveSmallIntegerField()),
                ('Min1', models.PositiveSmallIntegerField(default=3)),
                ('Min18', models.PositiveSmallIntegerField(default=3)),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRPR.games')),
            ],
            options={
                'db_table': 'FortyGroupRule',
                'indexes': [models.Index(fields=['Game', 'GroupID'], name='FortyGroupR_Game_id_99b2fe_idx')],
                'unique_together': {('Game', 'GroupID')},
            },
        ),
    ]
